version: '2.4'

services:
  tests:
    build:
      context: .
      target: tests

    command: >
      /bin/bash run_tests_linters.sh /mnt

    environment:
      PYTHONPATH: /mnt
      PYTHONDONTWRITEBYTECODE: 1
