"""empty message

Revision ID: init_schema
Revises: init_schema
Create Date: 2022-05-03 08:27:01.397229

"""
# pylint: skip-file; noqa

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "init_schema"
down_revision = "init_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
