"""empty message

Revision ID: init_schema
Revises: 
Create Date: 2022-03-11 22:07:08.285035

"""
# pylint: skip-file; noqa

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "init_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schemas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("owner", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schemas")
    # ### end Alembic commands ###
